version: '2'
services:
  php-nginx-fine:
    image: 192.168.11.249:80/test/php-nginx-fine:v1.1
    stdin_open: true
    tty: true
    links:
    - mysql-fine:mysql-fine
    ports:
    - 8005:80/tcp
    labels:
      io.rancher.container.pull_image: always
  mysql-fine:
    image: 192.168.11.249:80/test/mysql_fine:v1.1
    stdin_open: true
    tty: true
    ports:
    - 3306:3306/tcp
